</thead>
<tbody>
<tr><td>open</td><td>https://www.saucedemo.com/inventory.html<datalist><option>https://www.saucedemo.com/inventory.html</option></datalist></td><td></td></tr>
<tr><td>click</td><td>id=add-to-cart-sauce-labs-backpack<datalist><option>id=add-to-cart-sauce-labs-backpack</option><option>name=add-to-cart-sauce-labs-backpack</option><option>xpath=//button[@id='add-to-cart-sauce-labs-backpack']</option><option>xpath=//div[@id='inventory_container']/div/div/div[2]/div[2]/button</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='$29.99'])[1]/following::button[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Sauce Labs Backpack'])[1]/following::button[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Sauce Labs Bike Light'])[1]/preceding::button[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='$9.99'])[1]/preceding::button[1]</option><option>xpath=//*/text()[normalize-space(.)='Add to cart']/parent::*</option><option>xpath=//div[2]/div[2]/button</option><option>css=#add-to-cart-sauce-labs-backpack</option></datalist></td><td></td></tr>
<tr><td>click</td><td>id=add-to-cart-sauce-labs-bike-light<datalist><option>id=add-to-cart-sauce-labs-bike-light</option><option>name=add-to-cart-sauce-labs-bike-light</option><option>xpath=//button[@id='add-to-cart-sauce-labs-bike-light']</option><option>xpath=//div[@id='inventory_container']/div/div[2]/div[2]/div[2]/button</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='$9.99'])[1]/following::button[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Sauce Labs Bike Light'])[1]/following::button[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Sauce Labs Bolt T-Shirt'])[1]/preceding::button[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='$15.99'])[1]/preceding::button[1]</option><option>xpath=//*/text()[normalize-space(.)='Add to cart']/parent::*</option><option>xpath=//div[2]/div[2]/div[2]/button</option><option>css=#add-to-cart-sauce-labs-bike-light</option></datalist></td><td></td></tr>
<tr><td>click</td><td>id=add-to-cart-sauce-labs-bolt-t-shirt<datalist><option>id=add-to-cart-sauce-labs-bolt-t-shirt</option><option>name=add-to-cart-sauce-labs-bolt-t-shirt</option><option>xpath=//button[@id='add-to-cart-sauce-labs-bolt-t-shirt']</option><option>xpath=//div[@id='inventory_container']/div/div[3]/div[2]/div[2]/button</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='$15.99'])[1]/following::button[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Sauce Labs Bolt T-Shirt'])[1]/following::button[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Sauce Labs Fleece Jacket'])[1]/preceding::button[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='$49.99'])[1]/preceding::button[1]</option><option>xpath=//*/text()[normalize-space(.)='Add to cart']/parent::*</option><option>xpath=//div[3]/div[2]/div[2]/button</option><option>css=#add-to-cart-sauce-labs-bolt-t-shirt</option></datalist></td><td></td></tr>
<tr><td>click</td><td>id=add-to-cart-sauce-labs-fleece-jacket<datalist><option>id=add-to-cart-sauce-labs-fleece-jacket</option><option>name=add-to-cart-sauce-labs-fleece-jacket</option><option>xpath=//button[@id='add-to-cart-sauce-labs-fleece-jacket']</option><option>xpath=//div[@id='inventory_container']/div/div[4]/div[2]/div[2]/button</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='$49.99'])[1]/following::button[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Sauce Labs Fleece Jacket'])[1]/following::button[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Sauce Labs Onesie'])[1]/preceding::button[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='$7.99'])[1]/preceding::button[1]</option><option>xpath=//*/text()[normalize-space(.)='Add to cart']/parent::*</option><option>xpath=//div[4]/div[2]/div[2]/button</option><option>css=#add-to-cart-sauce-labs-fleece-jacket</option></datalist></td><td></td></tr>
<tr><td>click</td><td>xpath=//div[@id='shopping_cart_container']/a/span<datalist><option>xpath=//div[@id='shopping_cart_container']/a/span</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Swag Labs'])[2]/following::span[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Close Menu'])[1]/following::span[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Products'])[1]/preceding::span[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Name (A to Z)'])[1]/preceding::span[2]</option><option>xpath=//*/text()[normalize-space(.)='4']/parent::*</option><option>xpath=//span</option><option>css=span.shopping_cart_badge</option></datalist></td><td></td></tr>
<tr><td>open</td><td>https://www.saucedemo.com/cart.html<datalist><option>https://www.saucedemo.com/cart.html</option></datalist></td><td></td></tr>
<tr><td>click</td><td>id=checkout<datalist><option>id=checkout</option><option>name=checkout</option><option>xpath=//button[@id='checkout']</option><option>xpath=//div[@id='cart_contents_container']/div/div[2]/button[2]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Continue Shopping'])[1]/following::button[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[4]/following::button[2]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Twitter'])[1]/preceding::button[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Facebook'])[1]/preceding::button[1]</option><option>xpath=//*/text()[normalize-space(.)='Checkout']/parent::*</option><option>xpath=//button[2]</option><option>css=#checkout</option></datalist></td><td></td></tr>
<tr><td>open</td><td>https://www.saucedemo.com/checkout-step-one.html<datalist><option>https://www.saucedemo.com/checkout-step-one.html</option></datalist></td><td></td></tr>
<tr><td>click</td><td>id=first-name<datalist><option>id=first-name</option><option>name=firstName</option><option>xpath=//input[@id='first-name']</option><option>xpath=//div[@id='checkout_info_container']/div/form/div/div/input</option><option>xpath=//input</option><option>css=#first-name</option></datalist></td><td></td></tr>
<tr><td>type</td><td>id=first-name<datalist><option>id=first-name</option><option>name=firstName</option><option>xpath=//input[@id='first-name']</option><option>xpath=//div[@id='checkout_info_container']/div/form/div/div/input</option><option>xpath=//input</option><option>css=#first-name</option></datalist></td><td>Anne</td></tr>
<tr><td>click</td><td>id=last-name<datalist><option>id=last-name</option><option>name=lastName</option><option>xpath=//input[@id='last-name']</option><option>xpath=//div[@id='checkout_info_container']/div/form/div/div[2]/input</option><option>xpath=//div/div[2]/input</option><option>css=#last-name</option></datalist></td><td></td></tr>
<tr><td>type</td><td>id=last-name<datalist><option>id=last-name</option><option>name=lastName</option><option>xpath=//input[@id='last-name']</option><option>xpath=//div[@id='checkout_info_container']/div/form/div/div[2]/input</option><option>xpath=//div/div[2]/input</option><option>css=#last-name</option></datalist></td><td>Ivana</td></tr>
<tr><td>click</td><td>id=postal-code<datalist><option>id=postal-code</option><option>name=postalCode</option><option>xpath=//input[@id='postal-code']</option><option>xpath=//div[@id='checkout_info_container']/div/form/div/div[3]/input</option><option>xpath=//div[3]/input</option><option>css=#postal-code</option></datalist></td><td></td></tr>
<tr><td>type</td><td>id=postal-code<datalist><option>id=postal-code</option><option>name=postalCode</option><option>xpath=//input[@id='postal-code']</option><option>xpath=//div[@id='checkout_info_container']/div/form/div/div[3]/input</option><option>xpath=//div[3]/input</option><option>css=#postal-code</option></datalist></td><td>12345</td></tr>
<tr><td>click</td><td>id=continue<datalist><option>id=continue</option><option>name=continue</option><option>xpath=//input[@id='continue']</option><option>xpath=//div[@id='checkout_info_container']/div/form/div[2]/input</option><option>xpath=//div[2]/input</option><option>css=#continue</option></datalist></td><td></td></tr>
<tr><td>open</td><td>https://www.saucedemo.com/checkout-step-two.html<datalist><option>https://www.saucedemo.com/checkout-step-two.html</option></datalist></td><td></td></tr>
<tr><td>click</td><td>id=finish<datalist><option>id=finish</option><option>name=finish</option><option>xpath=//button[@id='finish']</option><option>xpath=//div[@id='checkout_summary_container']/div/div[2]/div[9]/button[2]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Total: $114.44'])[1]/following::button[2]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Twitter'])[1]/preceding::button[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Facebook'])[1]/preceding::button[1]</option><option>xpath=//*/text()[normalize-space(.)='Finish']/parent::*</option><option>xpath=//button[2]</option><option>css=#finish</option></datalist></td><td></td></tr>
<tr><td>open</td><td>https://www.saucedemo.com/checkout-complete.html<datalist><option>https://www.saucedemo.com/checkout-complete.html</option></datalist></td><td></td></tr>
<tr><td>click</td><td>id=back-to-products<datalist><option>id=back-to-products</option><option>name=back-to-products</option><option>xpath=//button[@id='back-to-products']</option><option>xpath=//div[@id='checkout_complete_container']/button</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Your order has been dispatched, and will arrive just as fast as the pony can get there!'])[1]/following::button[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Thank you for your order!'])[1]/following::button[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Twitter'])[1]/preceding::button[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Facebook'])[1]/preceding::button[1]</option><option>xpath=//*/text()[normalize-space(.)='Back Home']/parent::*</option><option>xpath=//div/div[2]/button</option><option>css=#back-to-products</option></datalist></td><td></td></tr>
</tbody></table>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
    