</thead>
<tbody>
<tr><td>open</td><td>https://www.saucedemo.com/inventory.html<datalist><option>https://www.saucedemo.com/inventory.html</option></datalist></td><td></td></tr>
<tr><td>click</td><td>xpath=//div[@id='header_container']/div[2]/div/span/select<datalist><option>xpath=//div[@id='header_container']/div[2]/div/span/select</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Name (A to Z)'])[1]/following::select[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Products'])[1]/following::select[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Sauce Labs Backpack'])[1]/preceding::select[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='$29.99'])[1]/preceding::select[1]</option><option>xpath=//select</option><option>css=select.product_sort_container</option></datalist></td><td></td></tr>
<tr><td>click</td><td>xpath=//div[@id='header_container']/div[2]/div/span/select<datalist><option>xpath=//div[@id='header_container']/div[2]/div/span/select</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Name (A to Z)'])[1]/following::select[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Products'])[1]/following::select[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Sauce Labs Backpack'])[1]/preceding::select[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='$29.99'])[1]/preceding::select[1]</option><option>xpath=//select</option><option>css=select.product_sort_container</option></datalist></td><td></td></tr>
<tr><td>click</td><td>xpath=//div[@id='header_container']/div[2]/div/span/select<datalist><option>xpath=//div[@id='header_container']/div[2]/div/span/select</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Name (Z to A)'])[1]/following::select[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Products'])[1]/following::select[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Test.allTheThings() T-Shirt (Red)'])[1]/preceding::select[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='$15.99'])[1]/preceding::select[1]</option><option>xpath=//select</option><option>css=select.product_sort_container</option></datalist></td><td></td></tr>
<tr><td>click</td><td>xpath=//div[@id='header_container']/div[2]/div/span/select<datalist><option>xpath=//div[@id='header_container']/div[2]/div/span/select</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Price (low to high)'])[1]/following::select[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Products'])[1]/following::select[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='Sauce Labs Onesie'])[1]/preceding::select[1]</option><option>xpath=(.//*[normalize-space(text()) and normalize-space(.)='$7.99'])[1]/preceding::select[1]</option><option>xpath=//select</option><option>css=select.product_sort_container</option></datalist></td><td></td></tr>
</tbody></table>
<table cellpadding="1" cellspacing="1" border="1">
<thead>

    